version: '3.9'
services:
  api:
    build:
      context: ./api
    ports:
      - '3001:3001'
    volumes:
      - ./api:/app
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db

  web:
    build:
      context: ./web
    ports:
      - '3000:3000'
    volumes:
      - ./web:/app
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - api

  db:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    restart: unless-stopped
    ports:
      - '8978:8978'
    volumes:
      - cloudbeaver_data:/opt/cloudbeaver/workspace

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - api

volumes:
  cloudbeaver_data:
    driver: local
